services:
  postgres:
    container_name: hackathon-postgres
    image: postgres:16
    command: postgres -c 'max_connections=250'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hackathon
    volumes:
      - hackathon_pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d hackathon"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hackathon_pgdata:
